micronaut:
  application:
    name: strong-psychological-backend
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: temporary-secret-for-strong
